apiVersion: v1
kind: Pod
metadata:
  name: env
spec:
  containers:
  - name: nginx
    image: nginx 
    env:
    - name: course
      valueFrom:
            configMapKeyRef:
              name: course-configmap          
              key: course
    - name:  duration
      valueFrom:
            configMapKeyRef:
              name: course-configmap          
              key: duration